### ISSUE TITLE
Eero App

### ISSUE THREAD

**Issue by donavanbecker** [EricRabil/m1-ios-sideloader#1]
Tried this on the Eero app and still getting:

<img width="261" alt="Screen Shot 2021-11-10 at 11 03 31 AM" src="https://user-images.githubusercontent.com/9875439/141158918-b896bec8-e868-4160-ba07-3f350d632228.png">

**Comment by EricRabil** [comment]
Did you try both the vtool and regular patch? Also, curious whether you have AMFI enabled. Never tested this on a Mac besides my own, I have AMFI disabled and permissive security.

**Comment by EricRabil** [comment]
Also, can you send me the IPA/app you're trying to install? ericjrabil@gmail.com or drop a link

**Comment by donavanbecker** [comment]
Didn't try vtool but will try now, and I am guessing I have it enabled since I haven't changed anything.

Also emailed you the api.

**Comment by donavanbecker** [comment]
this is what I get with vtool:

<img width="260" alt="Screen Shot 2021-11-10 at 12 11 00 PM" src="https://user-images.githubusercontent.com/9875439/141169520-ea8380f0-4589-4be7-b3c5-67401bd07c5d.png">

**Comment by EricRabil** [comment]
App works on my mac with AMFI and SIP disabled.
